### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by shafua** [Viacheslav-Zelinskyi/test-task2#1]
API
- креденшелы (`databaseUser , databaseUserPassword , database`) не безопасно хранить в репах, по этому даже локальные креды стоит выносить в переменные окружения
- `/auth` роут предполагался для получения JWT (эту роль выполняет `/signIn`)
- авторизация не реализована — запросить и создать слоты может не аунтефицированный и не авторизированный пользователь
- При создании слота удаляется вся таблица, то есть приложением может пользоваться только один пользлователь
- в `/signIn`, если пользователя нет, то приложение завалиться на сравнении паролей `user.rows[0].paswd`
- отдаются все слоты в таблице, а не для запросившего пользователя
Front
- при каждом рендере дергается АПИ `auth`
- [**критичное**] **'react-schedule-selector' не реализует функционал задания**
- компоненты в реакте принято именовать с большой буквы в кемелКейсе, файлы содержащие их — идентично с именами компонентов

**Плюсы**

- bcrypt
- raw SQL
- работа с localStorage

На данный момент не можем засчитать тестовое (критичный момент с компонентом выбора слотов). Готовы произвести одну ревизию после исправлений.

**Comment by Viacheslav-Zelinskyi** [comment]
Уже исправил
